"""Manual verification harness: drives the seeded Kamatchipuram cluster
through one full weather-triggered run and sends all four Telegram message
types to a single chat ID (yours) so they can be checked on a phone. Also
the demo video driver -- see the docstring notes on determinism below.

Usage:
    uv run python -m scripts.trigger_scenario <your_chat_id> [--offline]

--offline skips live Bedrock calls entirely (deterministic canned
argument text, same claim provider proven in the Phase 3 gate test) --
useful for a fast, free, no-AWS-needed dry run of the message flow itself.
Default (no flag) makes one real Bedrock call per contested plot to get
genuine advocate argument text for the escalation message.

Determinism, read before assuming this is fully reproducible:
- The plot classification (too-green / fits / contested) comes from
  Phase 2's solver against a FIXED synthetic forecast and a FIXED
  synthetic weather series (same construction as the Phase 2/3 gate
  tests) -- this part is 100% deterministic and always reproduces the
  proven split: p01/p02 fit, p03/p04 contested, p05-p08 too green.
- The escalation ALWAYS fires for p03 vs p04 in this script, by
  construction -- it does not run the full pairwise negotiation loop
  (which depends on live LLM concessions and could, on a bad run,
  resolve instead of escalating). That would defeat "reproducible on
  demand." What negotiate_pair()/run_cluster() actually do when concedes
  values come back non-deterministically is exercised by the Phase 3
  test suite, not by this script.
- In the default (non --offline) mode, the *argument text* inside the
  escalation message is genuinely generated by a live Bedrock call --
  the wording will vary run to run, the fact that an escalation happens
  at all will not.
"""

from __future__ import annotations

import argparse
import sys
import time
from dataclasses import replace
from datetime import date, timedelta

import httpx
from dotenv import load_dotenv

from harvest_convoy.agents.contracts import AdvocateClaim, EscalationPayload
from harvest_convoy.agents.coordinator import build_plot_facts
from harvest_convoy.agronomy import crop_params
from harvest_convoy.agronomy.gdd import DailyTemperature
from harvest_convoy.models import Farmer
from harvest_convoy.scheduling.capacity import ForecastDay
from harvest_convoy.scheduling.solver import PlotOutcome, solve
from harvest_convoy.storage import get_storage
from harvest_convoy.telegram import notify, webhook
from harvest_convoy.telegram.client import TelegramClient
from scripts import seed_cluster

REFERENCE_TODAY = date(2026, 8, 16)
CURRENT_SEASON_ID = "2026-kuruvai"
# Fixed synthetic forecast: 1 usable day then rain -- forces contestation
# among the ready plots. Same fixture the Phase 2/3 gate tests use.
FIXED_FORECAST = [ForecastDay("d0", 0.0), ForecastDay("d1", 20.0)]
RAIN_THRESHOLD_MM = 5.0
CALLBACK_POLL_TIMEOUT_SECONDS = 20
CALLBACK_WAIT_MAX_SECONDS = 300


def _synthetic_days(transplant_date: date, today: date) -> list[DailyTemperature]:
    rate = crop_params.KURUVAI_MEAN_GDD_PER_DAY_THENI_ESTIMATED
    mean_temp = crop_params.T_BASE_C + rate
    n = (today - transplant_date).days + 1
    return [
        DailyTemperature(
            date=(transplant_date + timedelta(days=i)).isoformat(),
            t_max_c=mean_temp,
            t_min_c=mean_temp,
        )
        for i in range(n)
    ]


def _offline_argument(facts) -> str:
    if not facts.is_ready:
        return "Not ready; standing safely, no urgency."
    return f"{facts.days_past_maturity} days past maturity, {facts.acres} acres at risk."


def build_escalation(plots_by_id, decisions_by_id, storage, *, offline: bool) -> EscalationPayload:
    facts_a = build_plot_facts(plots_by_id["p03"], decisions_by_id["p03"], storage)
    facts_b = build_plot_facts(plots_by_id["p04"], decisions_by_id["p04"], storage)

    if offline:
        argument_a = _offline_argument(facts_a)
        argument_b = _offline_argument(facts_b)
    else:
        from harvest_convoy.agents.advocate import get_advocate_claim

        print("Calling live Bedrock for p03's advocate argument...")
        argument_a = get_advocate_claim(facts_a, storage=storage).argument
        print("Calling live Bedrock for p04's advocate argument...")
        argument_b = get_advocate_claim(facts_b, storage=storage).argument

    claim_a = AdvocateClaim.from_facts(facts_a, argument=argument_a, concedes=False)
    claim_b = AdvocateClaim.from_facts(facts_b, argument=argument_b, concedes=False)

    return EscalationPayload(
        cluster_id=seed_cluster.CLUSTER.cluster_id,
        plot_a_id="p03",
        plot_b_id="p04",
        claim_a=claim_a,
        claim_b=claim_b,
        rounds_run=3,
        reason="No clear resolution after max negotiation rounds.",
    )


def wait_for_resolution(client: TelegramClient, storage, lookup) -> bool:
    """Long-poll getUpdates until the escalation callback arrives, or
    CALLBACK_WAIT_MAX_SECONDS elapses. Returns True if resolved."""
    print(
        f"\nWaiting up to {CALLBACK_WAIT_MAX_SECONDS}s for you to tap a button "
        f"on the escalation message... (Ctrl+C to stop waiting)"
    )
    deadline = time.time() + CALLBACK_WAIT_MAX_SECONDS
    offset = None
    while time.time() < deadline:
        params = {"timeout": CALLBACK_POLL_TIMEOUT_SECONDS}
        if offset is not None:
            params["offset"] = offset
        try:
            response = httpx.get(
                f"https://api.telegram.org/bot{client.token}/getUpdates",
                params=params,
                timeout=CALLBACK_POLL_TIMEOUT_SECONDS + 5.0,
            )
            response.raise_for_status()
            data = response.json()
        except Exception as exc:  # noqa: BLE001
            print(f"getUpdates failed: {exc}; retrying")
            time.sleep(2)
            continue

        for update in data.get("result", []):
            offset = update["update_id"] + 1
            if "callback_query" in update:
                webhook.handle_update(
                    client, update, storage, CURRENT_SEASON_ID,
                    lookup_farmer_for_plot=lookup,
                )
                return True
            # Not a callback -- still consume it so it doesn't get replayed.
    return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("chat_id", type=int, help="Your Telegram chat ID")
    parser.add_argument(
        "--offline", action="store_true",
        help="Skip live Bedrock calls; use canned deterministic argument text.",
    )
    args = parser.parse_args()

    load_dotenv()
    client = TelegramClient()
    if not client.token:
        print("TELEGRAM_BOT_TOKEN not set. Copy .env.example to .env and fill it in.")
        sys.exit(1)

    chat_id = args.chat_id
    storage = get_storage()

    # Everyone's chat_id is overridden to yours -- this is a solo
    # verification run, not a multi-farmer broadcast.
    farmers_by_id = {
        f.farmer_id: replace(f, telegram_chat_id=chat_id) for f in seed_cluster.FARMERS
    }
    plots_by_id = {p.plot_id: p for p in seed_cluster.PLOTS}
    cluster = replace(seed_cluster.CLUSTER, operator_chat_id=chat_id)

    print("Computing plot classification from the fixed synthetic scenario...")
    plot_days = {
        p.plot_id: _synthetic_days(p.transplant_date, REFERENCE_TODAY)
        for p in seed_cluster.PLOTS
    }
    decisions = solve(
        seed_cluster.PLOTS, plot_days, cluster, FIXED_FORECAST,
        rain_threshold_mm=RAIN_THRESHOLD_MM, today=REFERENCE_TODAY,
    )
    decisions_by_id = {d.plot_id: d for d in decisions}
    for d in decisions:
        print(f"  {d.plot_id}: {d.outcome.value}")

    def farmer_of(plot_id: str) -> Farmer:
        return farmers_by_id[plots_by_id[plot_id].farmer_id]

    print("\n1/4 Sending 'harvest scheduled' (p01)...")
    result = notify.send_harvest_scheduled(
        client, farmer_of("p01"), plots_by_id["p01"],
        route_position=decisions_by_id["p01"].route_position,
    )
    print(f"    success={result.success} error={result.error}")

    print("\n2/4 Sending 'no action needed' -- too-green (p07)...")
    result = notify.send_not_ready(client, farmer_of("p07"), plots_by_id["p07"])
    print(f"    success={result.success} error={result.error}")

    print("\n3/4 Sending operator route summary...")
    fits = sorted(
        (d for d in decisions if d.outcome == PlotOutcome.FITS),
        key=lambda d: d.route_position,
    )
    route = [(farmer_of(d.plot_id), plots_by_id[d.plot_id]) for d in fits]
    result = notify.send_operator_route_summary(
        client, cluster.operator_chat_id, cluster, route
    )
    route_labels = [notify.short_label(f, p) for f, p in route]
    print(f"    route={route_labels} success={result.success} error={result.error}")

    print("\n4/4 Building and sending the escalation (p03 vs p04)...")
    escalation = build_escalation(plots_by_id, decisions_by_id, storage, offline=args.offline)
    webhook.register_escalation(escalation)
    result = notify.send_escalation(
        client, cluster.operator_chat_id,
        escalation.cluster_id,
        escalation.plot_a_id, farmer_of("p03"), plots_by_id["p03"], escalation.claim_a,
        escalation.plot_b_id, farmer_of("p04"), plots_by_id["p04"], escalation.claim_b,
    )
    print(f"    success={result.success} error={result.error}")

    def lookup(plot_id: str):
        if plot_id not in plots_by_id:
            return None
        return farmer_of(plot_id), plots_by_id[plot_id]

    resolved = wait_for_resolution(client, storage, lookup)
    if resolved:
        print("\nEscalation resolved -- check your phone for the two resolution messages.")
    else:
        print(
            "\nNo tap received within the wait window. The escalation message "
            "is still live on your phone; run this script again or use "
            "scripts/run_polling.py if you want to tap it later (note: "
            "run_polling.py's default lookup won't resolve it -- see ADR-004)."
        )


if __name__ == "__main__":
    main()
